version: 2.1

jobs:
  build-and-run:
    docker:
      - image: hlohaus789/g4f:latest
    steps:
      - checkout
      - run:
          name: Install CloudFlare
          command: |
            echo "Installing CloudFlare..."
            curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
            sudo dpkg -i cloudflared.deb
            sudo cloudflared service install eyJhIjoiMWE1MTc4MTE0YTZjOWZmNDllMzZiNmMxNzVlOTZiYjkiLCJ0IjoiMjYzOTZhNWMtYmMzOC00NjZlLThiMDgtMDNjZWM4Njg5ODFmIiwicyI6IlltTmhNRGs1WTJZdE5EaGhaQzAwTVRRNUxUZ3hOVGd0Tm1GaE16ZzBZemxqTkdZMiJ9
      - store_artifacts:
          path: .
          destination: artifacts

workflows:
  version: 2
  build-and-run:
    jobs:
      - build-and-run:
          filters:
            branches:
              only: main
