version: 2.1

jobs:
  setup:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            curl -L https://coder.com/install.sh | sh
            coder server

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
