version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: ubuntu-executor
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Make Ptero directories
          command: |
            sudo mkdir -p /etc/pterodactyl
            curl -L -o /usr/local/bin/wings "https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_$([[ "$(uname -m)" == "x86_64" ]] && echo "amd64" || echo "arm64")"
            sudo chmod u+x /usr/local/bin/wings

      - run:
          name: Install Neofetch
          command: |
            sudo apt update
            sudo apt install -y neofetch

      - run:
          name: Neofetch
          command: neofetch

      - run:
          name: Domain Setup
          command: |
            sudo mkdir -p /etc/letsencrypt/live/usa1.hyghj.eu.org
            cd /etc/letsencrypt/live/usa1.hyghj.eu.org
            sudo openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 -subj "/C=NA/ST=NA/L=NA/O=NA/CN=Generic SSL Certificate" -keyout privkey.pem -out fullchain.pem

      - run:
          name: CFTunnel Installation
          command: |
            curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
            sudo dpkg -i cloudflared.deb
            sudo cloudflared service install eyJhIjoiMWE1MTc4MTE0YTZjOWZmNDllMzZiNmMxNzVlOTZiYjkiLCJ0IjoiNjU1ODcxYzUtYTc2MC00NTQzLWEzN2ItMzY5NjliYzQ0ZThlIiwicyI6IlltWmlOVGcyTjJVdFpHRXhOUzAwTkRVekxUbGxaREV0T1RCak56UXdObVptWVRSayJ9

      - run:
          name: Wings Configuration
          command: |
            cd /etc/pterodactyl
            sudo wings configure --panel-url https://panel.astralaxis.one --token ptla_ow7tyaIqnPooG1uX2mcVf0aVAkQUdOl1qLzF6wxJE1P --node 14

      - run:
          name: Get IP Address
          command: hostname -I | awk '{print $1}'

      - run:
          name: Start Wings
          command: sudo wings --debug

workflows:
  version: 2
  build:
    jobs:
      - build
