version: 2.1

jobs:
  setup:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y shellinabox
            echo 'root:root' | chpasswd
            shellinaboxd -t -s /:LOGIN

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
