version: 2.1

jobs:
  build-and-run:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install CloudFlare
          command: |
            echo "Installing CloudFlare..."
            curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
            sudo dpkg -i cloudflared.deb
            sudo cloudflared service install eyJhIjoiMWE1MTc4MTE0YTZjOWZmNDllMzZiNmMxNzVlOTZiYjkiLCJ0IjoiMjYzOTZhNWMtYmMzOC00NjZlLThiMDgtMDNjZWM4Njg5ODFmIiwicyI6IlltTmhNRGs1WTJZdE5EaGhaQzAwTVRRNUxUZ3hOVGd0Tm1GaE16ZzBZemxqTkdZMiJ9
      - run:
          name: Build Docker image
          command: |
            echo "Building Docker image..."
            docker build -t hlohaus789/g4f:latest .
      - run:
          name: Run container
          command: |
            echo "Running container..."
            docker run \
              -p 8080:8080 \
              -p 1337:1337 \
              -p 7900:7900 \
              --shm-size="2g" \
              -v ${PWD}/har_and_cookies:/app/har_and_cookies \
              -v ${PWD}/generated_images:/app/generated_images \
              hlohaus789/g4f:latest
      - store_artifacts:
          path: .
          destination: artifacts

workflows:
  version: 2
  build-and-run:
    jobs:
      - build-and-run:
          filters:
            branches:
              only: main
