version: 2.1

jobs:
  setup:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:
          name: Install Dependencies
          no_output_timeout: 8760h
          command: |
            apt install update
            apt install sudo curl -y
            curl -fsSL https://code-server.dev/install.sh | sh
            curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 
            sudo dpkg -i cloudflared.deb && sudo cloudflared service install eyJhIjoiMWE1MTc4MTE0YTZjOWZmNDllMzZiNmMxNzVlOTZiYjkiLCJ0IjoiZjdjNWU2ZGItMzE3My00MjNhLWI2ZDQtMjAyNzU2MjNlNDE0IiwicyI6Ik5qQmlObVV3TWpNdFlUQXpaQzAwWVdWa0xUaGpZVE10WmpsaU1qQmtZV1JpTURRMSJ9
            code-server --auth none
            

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
