version: 2.1

jobs:
  setup:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y build-essential libssl-dev libxml2-dev libxslt-dev python3 python3-pip
      - run:
          name: Clone SiaX
          command: |
            git clone https://github.com/shellinabox/shellinabox.git
            cd shellinabox
      - run:
          name: Install SiaX
          command: |
            pip3 install .
      - run:
          name: Configure SiaX
          command: |
            mkdir -p /var/www/html
            echo "shellinaboxd" > /etc/init.d/shellinaboxd
            chmod +x /etc/init.d/shellinaboxd
      - run:
          name: Start SiaX
          command: |
            service shellinaboxd start

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
