version: 2.1

jobs:
  setup:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            curl -fsSL https://code-server.dev/install.sh | sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
